package cli

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/spf13/cobra"
	"go.yaml.in/yaml/v3"

	"github.com/akynte/boundedcode/internal/benchmark"
	"github.com/akynte/boundedcode/internal/config"
	"github.com/akynte/boundedcode/internal/orchestrator"
	"github.com/akynte/boundedcode/internal/repointel/cbm"
	"github.com/akynte/boundedcode/internal/repointel/serena"
	"github.com/akynte/boundedcode/internal/store"
)

func newBenchCmd(app *App) *cobra.Command {
	cmd := &cobra.Command{Use: "bench", Short: "Run reproducible benchmarks"}
	cmd.AddCommand(newBenchInfraCmd(app), newBenchTasksCmd(app), newBenchIntelCmd(app))
	return cmd
}

func newBenchInfraCmd(app *App) *cobra.Command {
	var (
		modelName string
		opt       benchmark.InfraOptions
		sustained time.Duration
		outDir    string
		apply     bool
		onlyCfg   []string
	)
	cmd := &cobra.Command{
		Use:   "infra",
		Short: "Sweep inference-server settings and measure load, memory, prompt/decode speed and thermals",
		Long: `Finds, for each context size and KV cache type, the minimum number of MoE
layers that must stay in system RAM (n_cpu_moe) to fit in VRAM, then measures
nearby configurations with real requests. Results are written as JSON and
Markdown and recorded in the state database. With --apply the recommended
settings are saved as a user profile override.

This stops any managed llama-server and takes a long time (tens of minutes).`,
		RunE: func(cmd *cobra.Command, _ []string) error {
			if app.Config.Inference.Mode != "managed" {
				return fmt.Errorf("infra benchmarks need inference.mode: managed")
			}
			p, err := app.profile(modelName)
			if err != nil {
				return err
			}
			opt.Profile, opt.Sustained = p, sustained
			for _, c := range onlyCfg {
				var cf benchmark.Config
				if _, err := fmt.Sscanf(strings.ReplaceAll(c, ":", " "), "%d %s %d %d", &cf.CtxSize, &cf.CacheType, &cf.UBatch, &cf.NCPUMoE); err != nil {
					return fmt.Errorf("--config %q: want ctx:kv:ubatch:n_cpu_moe", c)
				}
				opt.Only = append(opt.Only, cf)
			}
			if err := os.MkdirAll(outDir, 0o755); err != nil {
				return err
			}
			stamp := time.Now().UTC().Format("20060102T150405Z")
			base := filepath.Join(outDir, fmt.Sprintf("%s-infra-%s", stamp, p.Name))
			opt.OutPath = base + ".json"
			runner := &benchmark.InfraRunner{Mgr: app.llamaManager(), Log: app.Log,
				Progress: func(s string) { fmt.Fprintf(app.Err, "%s %s\n", time.Now().Format("15:04:05"), s) }}
			rep, runErr := runner.Run(cmd.Context(), opt)
			var md bytes.Buffer
			if err := benchmark.WriteInfraMarkdown(&md, rep); err != nil {
				return err
			}
			if err := os.WriteFile(base+".md", md.Bytes(), 0o644); err != nil {
				return err
			}
			if err := recordBenchmark(cmd, app, rep.ID, "infra", p.Name, opt, rep); err != nil {
				return err
			}
			app.printf("report: %s.{json,md}\n", base)
			if runErr != nil {
				return runErr
			}
			if rep.Recommended == nil {
				return fmt.Errorf("no configuration met the constraints")
			}
			rc := rep.Recommended
			app.printf("recommended: ctx=%d kv=%s ubatch=%d n_cpu_moe=%d decode=%.1f t/s prompt=%.0f t/s\n",
				rc.CtxSize, rc.CacheType, rc.UBatch, rc.NCPUMoE, rc.DecodeTPS, rc.PromptTPS)
			if apply {
				np := p
				np.Server.CtxSize, np.Server.CacheTypeK, np.Server.CacheTypeV = rc.CtxSize, rc.CacheType, rc.CacheType
				np.Server.UBatchSize, np.Server.NCPUMoE = rc.UBatch, rc.NCPUMoE
				np.Server.BatchSize = max(np.Server.BatchSize, rc.UBatch)
				if np.Server.Parallel == 0 {
					np.Server.Parallel = 1
				}
				b, err := yaml.Marshal(np)
				if err != nil {
					return err
				}
				header := fmt.Sprintf("# Generated by `bench infra --apply` from report %s.\n", rep.ID)
				dst := filepath.Join(app.Paths.Config, "models", p.Name+".yaml")
				if err := config.WriteFileAtomic(dst, append([]byte(header), b...), 0o600); err != nil {
					return err
				}
				app.printf("applied to %s\n", dst)
			}
			return nil
		},
	}
	f := cmd.Flags()
	f.StringVarP(&modelName, "model", "m", "", "model profile")
	f.IntSliceVar(&opt.CtxSizes, "ctx", []int{32768, 65536}, "context sizes")
	f.StringSliceVar(&opt.CacheTypes, "kv", []string{"q8_0"}, "KV cache types (f16, q8_0, q4_0)")
	f.IntSliceVar(&opt.UBatches, "ubatch", []int{512}, "physical batch sizes")
	f.IntVar(&opt.MoESpan, "moe-span", 4, "measure n_cpu_moe from the minimum up to minimum+span (step 2)")
	f.IntVar(&opt.MoEMax, "moe-max", 40, "number of MoE layers in the model")
	f.IntSliceVar(&opt.PromptSizes, "prompt", []int{2048, 8192, 24576, 49152}, "prompt sizes in tokens")
	f.IntVar(&opt.DecodeTokens, "decode", 128, "tokens to generate per request")
	f.IntVar(&opt.MinFreeVRAMMiB, "min-free-vram", 300, "VRAM headroom (MiB) required for a recommendation")
	f.DurationVar(&sustained, "sustained", 0, "sustained decode run on the recommended config (e.g. 10m)")
	f.StringVar(&outDir, "out", "benchmarks/reports", "output directory")
	f.BoolVar(&apply, "apply", false, "save the recommended settings as a user profile override")
	f.StringSliceVar(&onlyCfg, "config", nil, "measure only these configs: ctx:kv:ubatch:n_cpu_moe (repeatable), skipping the search")
	f.BoolVar(&opt.ColdLoad, "cold", false, "evict the model from the page cache before each load (true cold-load times)")
	f.StringVar(&opt.Conditions, "conditions", "", "note about run conditions (e.g. \"idle, AC power\")")
	return cmd
}

func recordBenchmark(cmd *cobra.Command, app *App, id, kind, modelName string, cfg, result any) error {
	s, err := app.Store(cmd.Context())
	if err != nil {
		return err
	}
	cj, _ := json.Marshal(cfg)
	rj, _ := json.Marshal(result)
	mj, _ := json.Marshal(map[string]any{"hostname": hostname()})
	_, err = s.DB.ExecContext(cmd.Context(),
		`INSERT OR REPLACE INTO benchmark_runs(id, kind, model, config, result, machine, created_at) VALUES(?,?,?,?,?,?,?)`,
		id, kind, modelName, string(cj), string(rj), string(mj), store.Now())
	return err
}

func hostname() string {
	h, _ := os.Hostname()
	return h
}

func newBenchTasksCmd(app *App) *cobra.Command {
	var (
		dir, out, fixtures string
		only               []string
		rf                 runFlags
	)
	cmd := &cobra.Command{
		Use:   "tasks",
		Short: "Run the engineering benchmark suite (hidden acceptance checks) with the real agent",
		RunE: func(cmd *cobra.Command, _ []string) error {
			ctx := cmd.Context()
			tasks, err := benchmark.LoadTasks(dir)
			if err != nil {
				return err
			}
			if len(only) > 0 {
				var sel []benchmark.TaskSpec
				for _, t := range tasks {
					if contains(only, t.ID) || contains(only, t.Category) {
						sel = append(sel, t)
					}
				}
				tasks = sel
			}
			if len(tasks) == 0 {
				return fmt.Errorf("no tasks selected")
			}
			p, err := app.profile(rf.model)
			if err != nil {
				return err
			}
			sb, err := app.sandbox(rf.unsafeNoSandbox)
			if err != nil {
				return err
			}
			// Scratch space must be visible to the container engine (Docker
			// Desktop shares $HOME, not /tmp).
			work := filepath.Join(app.Paths.Cache, "bench-work")
			if err := os.MkdirAll(work, 0o700); err != nil {
				return err
			}
			stamp := time.Now().UTC().Format("20060102T150405Z")
			if out == "" {
				out = filepath.Join("benchmarks", "reports", fmt.Sprintf("%s-tasks-%s.json", stamp, p.Name))
			}
			sr := &benchmark.SuiteRunner{FixturesDir: fixtures, WorkRoot: work, Sandbox: sb,
				Progress: func(s string) { fmt.Fprintf(app.Err, "%s %s\n", time.Now().Format("15:04:05"), s) },
				NewRunner: func(ctx context.Context, stateDir string) (*orchestrator.Runner, func(), error) {
					paths := config.Paths{Runtime: app.Paths.Runtime, Config: app.Paths.Config, Data: filepath.Join(stateDir, "data"), Cache: filepath.Join(stateDir, "cache"), State: filepath.Join(stateDir, "state")}
					if err := paths.Ensure(); err != nil {
						return nil, nil, err
					}
					st, err := store.Open(ctx, paths.StateDB())
					if err != nil {
						return nil, nil, err
					}
					r, cleanup, err := app.buildRunnerWith(ctx, rf, st.DB, paths)
					if err != nil {
						st.Close()
						return nil, nil, err
					}
					r.Out = app.Err
					return r, func() { cleanup(); st.Close() }, nil
				}}
			rep, err := sr.Run(ctx, p.Name, tasks, out)
			if rep != nil {
				md := strings.TrimSuffix(out, ".json") + ".md"
				var b bytes.Buffer
				_ = benchmark.WriteSuiteMarkdown(&b, rep)
				_ = os.WriteFile(md, b.Bytes(), 0o644)
				_ = recordBenchmark(cmd, app, rep.ID, "engineering", p.Name, map[string]any{"tasks": len(tasks)}, rep)
				s := rep.Summary
				app.printf("verified %d/%d (%.0f%%), local-only %.0f%%, escalation rate %.0f%%, %.1f verified/hour, %.0fs/task\nreport: %s\n",
					s.Verified, s.Tasks, 100*s.SuccessRate, 100*s.LocalOnlyRate, 100*s.FrontierEscalationRate, s.VerifiedPerHour, s.MeanWallSeconds, md)
			}
			return err
		},
	}
	f := cmd.Flags()
	f.StringVar(&dir, "tasks", "benchmarks/tasks", "task definitions directory")
	f.StringVar(&fixtures, "fixtures", "benchmarks/fixtures", "fixtures directory")
	f.StringSliceVar(&only, "only", nil, "task ids or categories to run")
	f.StringVar(&out, "out", "", "report path (.json; .md written alongside)")
	addRunFlags(cmd, &rf)
	return cmd
}

func newBenchIntelCmd(app *App) *cobra.Command {
	var dir, fixtures, out string
	var only []string
	cmd := &cobra.Command{
		Use:   "intel",
		Short: "Overlap study: ask Serena, codebase-memory-mcp and a grep baseline the same ground-truth navigation questions",
		RunE: func(cmd *cobra.Command, _ []string) error {
			ctx := cmd.Context()
			specs, err := benchmark.LoadIntelSpecs(dir)
			if err != nil {
				return err
			}
			if len(only) > 0 {
				var sel []benchmark.IntelSpec
				for _, s := range specs {
					if contains(only, s.ID) {
						sel = append(sel, s)
					}
				}
				specs = sel
			}
			work := filepath.Join(app.Paths.Cache, "bench-work")
			if err := os.MkdirAll(work, 0o700); err != nil {
				return err
			}
			study := &benchmark.IntelStudy{FixturesDir: fixtures, WorkRoot: work,
				Progress: func(s string) { fmt.Fprintf(app.Err, "%s %s\n", time.Now().Format("15:04:05"), s) },
				Serena: func(root string) *serena.Manager {
					m := app.serenaManager(app.Paths)
					m.Root, m.MaxInstances = root, 1
					return m
				},
				Graph: func(cacheDir string) *cbm.Client {
					return &cbm.Client{Binary: app.Config.RepoIntel.Binary, CacheDir: cacheDir}
				},
			}
			if err := study.Serena("").Verify(ctx); err != nil {
				return fmt.Errorf("serena: %w (run `boundedcode serena setup`)", err)
			}
			var reps []*benchmark.IntelReport
			for _, s := range specs {
				r, err := study.Run(ctx, s)
				if err != nil {
					return fmt.Errorf("%s: %w", s.ID, err)
				}
				reps = append(reps, r)
			}
			stamp := time.Now().UTC().Format("20060102T150405Z")
			if out == "" {
				out = filepath.Join("benchmarks", "reports", stamp+"-intel-overlap.json")
			}
			b, _ := json.MarshalIndent(reps, "", "  ")
			if err := config.WriteFileAtomic(out, b, 0o644); err != nil {
				return err
			}
			var md bytes.Buffer
			_ = benchmark.WriteIntelMarkdown(&md, reps)
			mdPath := strings.TrimSuffix(out, ".json") + ".md"
			if err := os.WriteFile(mdPath, md.Bytes(), 0o644); err != nil {
				return err
			}
			app.printf("%s\nreport: %s\n", md.String(), mdPath)
			return nil
		},
	}
	f := cmd.Flags()
	f.StringVar(&dir, "specs", "benchmarks/intel", "study definitions directory")
	f.StringVar(&fixtures, "fixtures", "benchmarks/fixtures", "fixtures directory")
	f.StringSliceVar(&only, "only", nil, "study ids to run")
	f.StringVar(&out, "out", "", "report path (.json; .md written alongside)")
	return cmd
}
