package cli

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/spf13/cobra"
	"go.yaml.in/yaml/v3"

	"github.com/akynte/boundedcode/internal/benchmark"
	"github.com/akynte/boundedcode/internal/config"
	"github.com/akynte/boundedcode/internal/store"
)

func newBenchCmd(app *App) *cobra.Command {
	cmd := &cobra.Command{Use: "bench", Short: "Run reproducible benchmarks"}
	cmd.AddCommand(newBenchInfraCmd(app))
	return cmd
}

func newBenchInfraCmd(app *App) *cobra.Command {
	var (
		modelName string
		opt       benchmark.InfraOptions
		sustained time.Duration
		outDir    string
		apply     bool
	)
	cmd := &cobra.Command{
		Use:   "infra",
		Short: "Sweep inference-server settings and measure load, memory, prompt/decode speed and thermals",
		Long: `Finds, for each context size and KV cache type, the minimum number of MoE
layers that must stay in system RAM (n_cpu_moe) to fit in VRAM, then measures
nearby configurations with real requests. Results are written as JSON and
Markdown and recorded in the state database. With --apply the recommended
settings are saved as a user profile override.

This stops any managed llama-server and takes a long time (tens of minutes).`,
		RunE: func(cmd *cobra.Command, _ []string) error {
			if app.Config.Inference.Mode != "managed" {
				return fmt.Errorf("infra benchmarks need inference.mode: managed")
			}
			p, err := app.profile(modelName)
			if err != nil {
				return err
			}
			opt.Profile, opt.Sustained = p, sustained
			if err := os.MkdirAll(outDir, 0o755); err != nil {
				return err
			}
			stamp := time.Now().UTC().Format("20060102T150405Z")
			base := filepath.Join(outDir, fmt.Sprintf("%s-infra-%s", stamp, p.Name))
			opt.OutPath = base + ".json"
			runner := &benchmark.InfraRunner{Mgr: app.llamaManager(), Log: app.Log,
				Progress: func(s string) { fmt.Fprintf(app.Err, "%s %s\n", time.Now().Format("15:04:05"), s) }}
			rep, runErr := runner.Run(cmd.Context(), opt)
			var md bytes.Buffer
			if err := benchmark.WriteInfraMarkdown(&md, rep); err != nil {
				return err
			}
			if err := os.WriteFile(base+".md", md.Bytes(), 0o644); err != nil {
				return err
			}
			if err := recordBenchmark(cmd, app, rep.ID, "infra", p.Name, opt, rep); err != nil {
				return err
			}
			app.printf("report: %s.{json,md}\n", base)
			if runErr != nil {
				return runErr
			}
			if rep.Recommended == nil {
				return fmt.Errorf("no configuration met the constraints")
			}
			rc := rep.Recommended
			app.printf("recommended: ctx=%d kv=%s ubatch=%d n_cpu_moe=%d decode=%.1f t/s prompt=%.0f t/s\n",
				rc.CtxSize, rc.CacheType, rc.UBatch, rc.NCPUMoE, rc.DecodeTPS, rc.PromptTPS)
			if apply {
				np := p
				np.Server.CtxSize, np.Server.CacheTypeK, np.Server.CacheTypeV = rc.CtxSize, rc.CacheType, rc.CacheType
				np.Server.UBatchSize, np.Server.NCPUMoE = rc.UBatch, rc.NCPUMoE
				np.Server.BatchSize = max(np.Server.BatchSize, rc.UBatch)
				if np.Server.Parallel == 0 {
					np.Server.Parallel = 1
				}
				b, err := yaml.Marshal(np)
				if err != nil {
					return err
				}
				header := fmt.Sprintf("# Generated by `bench infra --apply` from report %s.\n", rep.ID)
				dst := filepath.Join(app.Paths.Config, "models", p.Name+".yaml")
				if err := config.WriteFileAtomic(dst, append([]byte(header), b...), 0o600); err != nil {
					return err
				}
				app.printf("applied to %s\n", dst)
			}
			return nil
		},
	}
	f := cmd.Flags()
	f.StringVarP(&modelName, "model", "m", "", "model profile")
	f.IntSliceVar(&opt.CtxSizes, "ctx", []int{32768, 65536}, "context sizes")
	f.StringSliceVar(&opt.CacheTypes, "kv", []string{"q8_0"}, "KV cache types (f16, q8_0, q4_0)")
	f.IntSliceVar(&opt.UBatches, "ubatch", []int{512}, "physical batch sizes")
	f.IntVar(&opt.MoESpan, "moe-span", 4, "measure n_cpu_moe from the minimum up to minimum+span (step 2)")
	f.IntVar(&opt.MoEMax, "moe-max", 40, "number of MoE layers in the model")
	f.IntSliceVar(&opt.PromptSizes, "prompt", []int{2048, 8192, 24576, 49152}, "prompt sizes in tokens")
	f.IntVar(&opt.DecodeTokens, "decode", 128, "tokens to generate per request")
	f.IntVar(&opt.MinFreeVRAMMiB, "min-free-vram", 300, "VRAM headroom (MiB) required for a recommendation")
	f.DurationVar(&sustained, "sustained", 0, "sustained decode run on the recommended config (e.g. 10m)")
	f.StringVar(&outDir, "out", "benchmarks/reports", "output directory")
	f.BoolVar(&apply, "apply", false, "save the recommended settings as a user profile override")
	return cmd
}

func recordBenchmark(cmd *cobra.Command, app *App, id, kind, modelName string, cfg, result any) error {
	s, err := app.Store(cmd.Context())
	if err != nil {
		return err
	}
	cj, _ := json.Marshal(cfg)
	rj, _ := json.Marshal(result)
	mj, _ := json.Marshal(map[string]any{"hostname": hostname()})
	_, err = s.DB.ExecContext(cmd.Context(),
		`INSERT OR REPLACE INTO benchmark_runs(id, kind, model, config, result, machine, created_at) VALUES(?,?,?,?,?,?,?)`,
		id, kind, modelName, string(cj), string(rj), string(mj), store.Now())
	return err
}

func hostname() string {
	h, _ := os.Hostname()
	return h
}
