"""Classify licenses of every distribution installed in the adapter
environment and flag GPL/AGPL/SSPL/unknown ones (docs/licensing/policy.md).

usage: run it with the environment's interpreter, for example
  adapters/openhands/python/.venv/bin/python scripts/pylicensecheck.py --markdown adapters/openhands/python/THIRD_PARTY.md
  <serena-env>/.venv/bin/python scripts/pylicensecheck.py --markdown configs/serena/THIRD_PARTY.md
It exits 1 on a denied license. --markdown OUT rewrites the table in OUT and
keeps the text above it.
"""

import re
import sys
from importlib.metadata import distributions

DENY = re.compile(r"\b(A?GPL|GNU (Affero )?General Public|SSPL|Server Side Public|BUSL|Business Source|Commons Clause)", re.I)
LGPL = re.compile(r"\b(LGPL|Lesser General Public|Library General Public)", re.I)
REVIEW = re.compile(r"\b(MPL|Mozilla|EPL|Eclipse|CDDL|LGPL|Lesser General Public)", re.I)
ALLOW = re.compile(r"\b(MIT|BSD|Apache|ISC|PSF|Python Software Foundation|Unlicense|CC0|0BSD|Zlib|HPND|MIT-CMU)\b", re.I)


def license_of(d):
    md = d.metadata
    expr = md.get("License-Expression")
    if expr:
        return expr.strip()
    classifiers = [c.split("::")[-1].strip() for c in md.get_all("Classifier") or [] if c.startswith("License ::")]
    if classifiers:
        return "; ".join(classifiers)
    lic = (md.get("License") or "").strip()
    if lic and len(lic) < 120:
        return lic
    if lic:
        return lic.splitlines()[0][:120]
    return ""


SEVERITY = {"ok": 0, "REVIEW": 1, "UNKNOWN": 2, "DENY": 3}


def _split_top(text, op, flags=0):
    """Split text on a boolean operator outside parentheses."""
    parts, depth, cur, i = [], 0, "", 0
    pat = re.compile(r"\s+" + op + r"\s+", flags)
    while i < len(text):
        c = text[i]
        if c == "(":
            depth += 1
        elif c == ")":
            depth -= 1
        elif depth == 0:
            m = pat.match(text, i)
            if m:
                parts.append(cur)
                cur, i = "", m.end()
                continue
        cur += c
        i += 1
    parts.append(cur)
    return [x.strip() for x in parts if x.strip()]


def _wrapped(text):
    """Report whether the "(" at the start closes at the very end."""
    if not (text.startswith("(") and text.endswith(")")):
        return False
    depth = 0
    for i, c in enumerate(text):
        depth += c == "("
        depth -= c == ")"
        if depth == 0:
            return i == len(text) - 1
    return False


def _strip_parens(text):
    text = text.strip()
    while _wrapped(text):
        text = text[1:-1].strip()
    return text


def _single(text):
    if LGPL.search(text):
        return "REVIEW"
    if DENY.search(text):
        return "DENY"
    if REVIEW.search(text):
        return "REVIEW"
    if ALLOW.search(text):
        return "ok"
    return "UNKNOWN"


def classify(text):
    """Classify a license expression or classifier list.

    Every conjunct must pass: "MPL-2.0 AND (Apache-2.0 OR MIT)" needs review
    because of MPL-2.0. OR picks the most permissive option, but only within
    one conjunct. Several trove classifiers ("A; B") are treated as AND. AND
    splits only on the SPDX operator (upper case), so prose such as
    "Permission Notice and Disclaimer" stays one license; OR also splits on
    "or" ("GNU Library or Lesser General Public License").
    """
    if not text or not text.strip():
        return "UNKNOWN"
    worst = "ok"
    for part in re.split(r"\s*;\s*", text.strip()):
        if not part:
            continue
        for conj in _split_top(_strip_parens(part), "AND"):
            options = _split_top(_strip_parens(conj), "OR", re.I)
            if len(options) > 1:
                best = min((classify(o) for o in options), key=SEVERITY.get)
            else:
                best = _single(_strip_parens(conj))
            if SEVERITY[best] > SEVERITY[worst]:
                worst = best
    return worst


def main():
    rows = []
    for d in distributions():
        name = d.metadata.get("Name") or "?"
        lic = license_of(d)
        rows.append((classify(lic), name, d.version, lic))
    rows.sort(key=lambda r: (r[0] == "ok", r[1].lower()))
    bad = [r for r in rows if r[0] != "ok"]
    for v, n, ver, lic in bad:
        print(f"{v:7} {n}=={ver}: {lic or '(no metadata)'}")
    print(f"{len(rows)} distributions, {len(bad)} need attention")
    if "--markdown" in sys.argv:
        out = sys.argv[sys.argv.index("--markdown") + 1]
        # Keep a hand-written preamble (title, review notes) of an existing
        # file; only the table is regenerated.
        head = ("# Adapter environment licenses (generated)\n\nGenerated by `scripts/pylicensecheck.py`. "
                "This environment is installed locally or into a locally built image and is not redistributed by this project.\n\n")
        try:
            with open(out) as f:
                old = f.read()
            if "| verdict |" in old:
                head = old[: old.index("| verdict |")]
        except FileNotFoundError:
            pass
        with open(out, "w") as f:
            f.write(head + "| verdict | package | version | license (metadata) |\n|---|---|---|---|\n")
            for v, n, ver, lic in rows:
                f.write(f"| {v} | {n} | {ver} | {lic.replace('|', '/') or '(none)'} |\n")
    return 1 if any(r[0] == "DENY" for r in rows) else 0


if __name__ == "__main__":
    sys.exit(main())
