"""Classify licenses of every distribution installed in the adapter
environment and flag GPL/AGPL/SSPL/unknown ones (docs/licensing/policy.md).

usage: (cd adapters/openhands/python && uv run python ../../../scripts/pylicensecheck.py [--markdown OUT])
"""

import re
import sys
from importlib.metadata import distributions

DENY = re.compile(r"\b(A?GPL|GNU (Affero )?General Public|SSPL|Server Side Public|BUSL|Business Source|Commons Clause)", re.I)
LGPL = re.compile(r"\b(LGPL|Lesser General Public|Library General Public)", re.I)
REVIEW = re.compile(r"\b(MPL|Mozilla|EPL|Eclipse|CDDL|LGPL|Lesser General Public)", re.I)
ALLOW = re.compile(r"\b(MIT|BSD|Apache|ISC|PSF|Python Software Foundation|Unlicense|CC0|0BSD|Zlib|HPND|MIT-CMU)\b", re.I)


def license_of(d):
    md = d.metadata
    expr = md.get("License-Expression")
    if expr:
        return expr.strip()
    classifiers = [c.split("::")[-1].strip() for c in md.get_all("Classifier") or [] if c.startswith("License ::")]
    if classifiers:
        return "; ".join(classifiers)
    lic = (md.get("License") or "").strip()
    if lic and len(lic) < 120:
        return lic
    if lic:
        return lic.splitlines()[0][:120]
    return ""


def classify(text):
    if not text:
        return "UNKNOWN"
    # Dual/multi licenses: allowed if any allowed option exists (e.g. "MIT OR GPL").
    if " OR " in text or " or " in text:
        if ALLOW.search(text):
            return "ok"
    if LGPL.search(text):
        return "REVIEW"
    if DENY.search(text):
        return "DENY"
    if REVIEW.search(text):
        return "REVIEW"
    if ALLOW.search(text):
        return "ok"
    return "UNKNOWN"


def main():
    rows = []
    for d in distributions():
        name = d.metadata.get("Name") or "?"
        lic = license_of(d)
        rows.append((classify(lic), name, d.version, lic))
    rows.sort(key=lambda r: (r[0] == "ok", r[1].lower()))
    bad = [r for r in rows if r[0] != "ok"]
    for v, n, ver, lic in bad:
        print(f"{v:7} {n}=={ver}: {lic or '(no metadata)'}")
    print(f"{len(rows)} distributions, {len(bad)} need attention")
    if "--markdown" in sys.argv:
        out = sys.argv[sys.argv.index("--markdown") + 1]
        with open(out, "w") as f:
            f.write("# Adapter environment licenses (generated)\n\nGenerated by `scripts/pylicensecheck.py`. "
                    "This environment is installed locally or into a locally built image and is not redistributed by this project.\n\n"
                    "| verdict | package | version | license (metadata) |\n|---|---|---|---|\n")
            for v, n, ver, lic in rows:
                f.write(f"| {v} | {n} | {ver} | {lic.replace('|', '/') or '(none)'} |\n")
    return 1 if any(r[0] == "DENY" for r in rows) else 0


if __name__ == "__main__":
    sys.exit(main())
